import {AUTOWARE_WEB_UI_HOST, AUTOWARE_WEB_UI_PORT, AUTOWARE_ROSBRIDGE_HOST, AUTOWARE_ROSBRIDGE_PORT, AUTOWARE_ROSVIDEO_HOST, AUTOWARE_ROSVIDEO_PORT,MQTT_HOST,MQTT_JS_PORT} from "react-native-dotenv";

const WEB_UI_URL = "http://"+AUTOWARE_WEB_UI_HOST+":"+AUTOWARE_WEB_UI_PORT;
const ROSBRIDGE_URL = "ws://"+AUTOWARE_ROSBRIDGE_HOST+":"+AUTOWARE_ROSBRIDGE_PORT;
const ROSVIDEO_URL = "http://"+AUTOWARE_ROSVIDEO_HOST+":"+AUTOWARE_ROSVIDEO_PORT;
const MQTT_HOST_NAME = MQTT_HOST;
const MQTT_PORT = MQTT_JS_PORT;

export {WEB_UI_URL, ROSBRIDGE_URL, ROSVIDEO_URL,MQTT_HOST_NAME,MQTT_PORT};


