import {AUTOWARE_WEB_UI_HOST, AUTOWARE_WEB_UI_PORT, AUTOWARE_ROSBRIDGE_HOST, AUTOWARE_ROSBRIDGE_PORT, AUTOWARE_ROSVIDEO_HOST, AUTOWARE_ROSVIDEO_PORT} from "react-native-dotenv";

const WEB_UI_URL = "http://"+AUTOWARE_WEB_UI_HOST+":"+AUTOWARE_WEB_UI_PORT;
const ROSBRIDGE_URL = "ws://"+AUTOWARE_ROSBRIDGE_HOST+":"+AUTOWARE_ROSBRIDGE_PORT;
const ROSVIDEO_URL = "http://"+AUTOWARE_ROSVIDEO_HOST+":"+AUTOWARE_ROSVIDEO_PORT;
const MQTT_HOST = AUTOWARE_WEB_UI_HOST;
export {WEB_UI_URL, ROSBRIDGE_URL, ROSVIDEO_URL,MQTT_HOST};


